AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for lambda

Resources:
  CreateBooks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: build/handlers/create/create.handle
      Runtime: nodejs14.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /books
            Method: post

  GetBooks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: build/handlers/get-books/get-books.handle
      Runtime: nodejs14.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /books
            Method: get

  GetBook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: build/handlers/get-book/get-book.handle
      Runtime: nodejs14.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /books/{id}
            Method: get